### ISSUE TITLE
When pushing to forked repo, Jekyll error thrown.

### ISSUE THREAD

**Issue by krusynth** [statedecoded/documentation#7]
I don't know enough about Jekyll config to suggest a good solution here, but when I commit to my local fork of the documentation, it throws an error complaining about a duplicate CNAME.  That's to be expected, but I'm not sure if there's a good way to not have this error.

Error:

```
The page build failed with the following error:

CNAME already taken: documentation.statedecoded.com

For information on troubleshooting Jekyll see:

 https://help.github.com/articles/using-jekyll-with-pages#troubleshooting

If you have any questions please contact us at https://github.com/contact.
```

**Comment by waldoj** [comment]
This is an interesting problem. @benbalter, this seems like something that rises to the level of a potential bug (well, "bug" is slightly too strong of a word.) Is this a known issue? Is there any way to prevent it?

**Comment by benbalter** [comment]
Known expected, but annoying behavior. It's on the list to take a closer look at.

**Comment by krusynth** [comment]
Upstream issue.

**Comment by waldoj** [comment]
Thanks, Ben!
